name: End-To-End Cypress Test
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        containers: [1]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Cypress
        run: npm install -g cypress
      - name: Add Cypress to PATH
        run: export PATH=$(npm bin):$PATH
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          start: npm start
          wait-on: 'http://localhost:3000' 
          record: true
          parallel: true 
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.E2E_CYPRESS_RECORD_KEY }}